In [1]:
import numpy as np

### Q_train_test

In [8]:
class Q_train_test:
    
    Q_DUMP = "qlearner.pickle"
        
    def predict(self, new_state:int)->int:
        
        """ Predict next best action """
        
        self.current_state = new_state
        if rand.random() < self.rar:
            random_flag = True
            action = int(rand.randint(0, self.actions -1))
        else:
            random_flag = False
            action = int(np.argmax(self.q_values[self.current_state])  )                  
        self.current_action = action
        
        return(action, random_flag)

### Create a maze from csv

In [9]:
def csv_to_maze():
    
    """ Load csv file as a maze using file obj """
    
    file_path = "maze.csv"
    with open(file_path, encoding= "utf") as maze_file:
        maze_grid = np.array(
            [
                list(map(float, s.strip().split(",")))
                for s in maze_file.readlines()
            ]
        )
    return maze_grid

### Render maze

In [10]:
def render_maze(csv: np.ndarray):
    
    """ Renders a 2d map """
    
    #print(" ")
    print("..........")
    map_dictionary = {
                      0: " ", 
                      1: "*",
                      2: "X",
                      3: "Y",
                      9: "."}
    for row in range(0, csv.shape[0]):
        for col in range(0, csv.shape[1]):
            print(map_dictionary[csv[row,col]], end= " ")
        print()
    print("..........")

### Agent plays using persisted object

In [11]:
def test(start_positions, goal_x, goal_y, maze):
    print("Q Learner object loaded -->", Qlearner)
    print(" ")
    for start_x, start_y in start_positions:
        x,y = np.where(maze==1)
        maze[x,y] = 0
        maze[start_x,start_y]=1
        print(" ")
        print("Agent moves through the maze")
        print(" ")     
        done = False
        maze_b = maze.copy()   
        print("Testing agent with starting position at: ", "[", start_x, ",", start_y, "]")
        print(" ")
        print(maze_b)
        render_maze(maze_b)
        
        while not done:
            
            def discretize(curr_x:int, curr_y:int):
                return curr_x*10 + curr_y
            old_x, old_y = np.where(maze_b == 1)
            action, random_flag = Qlearner.predict(discretize(old_x, old_y))
            curr_x, curr_y = old_x, old_y
            #print("Maze Trajectory")
            if action == 0:  # left
                curr_y = old_y - 1
            elif action == 1:  # right
                curr_y = old_y + 1
            elif action == 2:  # up
                curr_x = old_x - 1
            else:  # down
                curr_x = old_x + 1
            maze_b[old_x, old_y] = 9
            maze_b[curr_x, curr_y] = 1
            old_x, old_y = curr_x, curr_y
            if (curr_x == goal_x) & (curr_y == goal_y):
                done = True
        print(" ")
        print("Final path chosen by agent:")
        render_maze(maze_b)
        assert done

In [12]:
import pickle
import random as rand
start_positions = [(6,0), (9,4)]
goal_x, goal_y = (0,2)
maze = csv_to_maze()
with open("qlearner.pickle", "rb")as file:
    Qlearner = pickle.load(file)
    
test(start_positions, goal_x, goal_y, maze)

Q Learner object loaded --> <__main__.Q_train_test object at 0x000001FD20AC3E80>
 
 
Agent moves through the maze
 
Testing agent with starting position at:  [ 6 , 0 ]
 
[[0. 0. 3. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 2. 0. 0. 2.]
 [0. 0. 2. 0. 0.]
 [2. 0. 0. 0. 2.]
 [0. 2. 0. 2. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 2. 2. 0.]
 [0. 0. 0. 0. 2.]
 [0. 2. 2. 0. 0.]]
..........
    Y     
      X   
  X     X 
    X     
X       X 
  X   X   
*         
  X X X   
        X 
  X X     
..........
 
Final path chosen by agent:
..........
    *     
    . X   
  X . . X 
    X .   
X   . . X 
  X . X   
. . .     
  X X X   
        X 
  X X     
..........
 
Agent moves through the maze
 
Testing agent with starting position at:  [ 9 , 4 ]
 
[[0. 0. 3. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 2. 0. 0. 2.]
 [0. 0. 2. 0. 0.]
 [2. 0. 0. 0. 2.]
 [0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 0.]
 [0. 0. 0. 0. 2.]
 [0. 2. 2. 0. 1.]]
..........
    Y     
      X   
  X     X 
    X     
X       X 
  X   X   
          